[profile.default]
names = true
fs_permissions = [
    { access = "read", path = "./out/"},
    { access = "read", path = "./config/"}
]
libs = ["lib"]
ignored_error_codes = ["transient-storage"]
ignored_warnings_from = ["test"]
via-ir = true
optimizer = true
optimizer_runs = 999999
bytecode_hash = "none"
evm_version = "cancun"

[profile.default.fuzz]
runs = 64

[profile.default.rpc_endpoints]
bsc = "https://bnb-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
tenderly = "https://rpc.tenderly.co/fork/${TENDERLY_FORK_ID}"

[profile.default.fmt]
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
